### ISSUE TITLE
Upgrade to node 23

### ISSUE THREAD

**Issue by maskeynihal** [kritish-dhaubanjar/dynamodb-dashboard#1112]
**Is your feature request related to a problem? Please describe.**
Upgrade to node 23

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kritish-dhaubanjar** [comment]
Getting `(node:97820) Warning: NodeDeprecationWarning: The AWS SDK for JavaScript (v3) will`

![image](https://github.com/user-attachments/assets/b7e6fbec-419c-4587-b432-38ab7b302eba)

**Comment by kritish-dhaubanjar** [comment]
Resolved in https://github.com/kritish-dhaubanjar/dynamodb-dashboard/commit/2b903663f33b1703e7b69271c32ef32e823d574d
