### ISSUE TITLE
Support the `ScanIndexForward` option in QUERY

### ISSUE THREAD

**Issue by chehsunliu** [kritish-dhaubanjar/dynamodb-dashboard#1174]
**Is your feature request related to a problem? Please describe.**

It seems the UI doesn't have the `ScanIndexForward` option to reverse the index traversal in QUERY: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#API_Query_RequestSyntax.

**Describe the solution you'd like**

Support the `ScanIndexForward` option in QUERY.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by kritish-dhaubanjar** [comment]
@chehsunliu, Working on adding `ScanIndexForward`. Here's the progress so far. Will include in the new release.

| Sort Ascending (default `true`) | Sort Descending |
|-|-|
|![image](https://github.com/user-attachments/assets/26a9e4dc-9f54-40d3-b854-a0bc336dc824)|![image](https://github.com/user-attachments/assets/e8fb7024-33f4-434e-847a-8e08d6814640)|

**Comment by chehsunliu** [comment]
BTW, I really like your UI. Very easy to use and also modern! Thanks!

**Comment by kritish-dhaubanjar** [comment]
I'm glad you like the UI. Thank you, I appreciate your kind words!
