### ISSUE TITLE
`ScanIndexForward` doesn't show up immediately in the query preview

### ISSUE THREAD

**Issue by chehsunliu** [kritish-dhaubanjar/dynamodb-dashboard#1176]
**Describe the bug**

`ScanIndexForward` doesn't show up immediately in the query preview.

**To Reproduce**

1. Visit http://localhost:8080.
2. Switch from `SCAN` to `QUERY`.
3. Type anything in the partition key to show the query preview.
4. Toggle the `Sort ascending` box.
5. Toggling should affect the query preview, but it doesn't. However, if the `RUN` button is clicked, the preview block will show the change immediately.

**Expected behavior**

Toggling should affect the query preview.

**Screenshots**

![image](https://github.com/user-attachments/assets/2377a4e3-fd32-4904-b55c-b8e952119ee9)

**Desktop:**
 - macOS `Sonoma 14.5`
 - Firefox `133.0.3 (aarch64)`
 - `kritishdhaubanjar/dynamodb-dashboard:v1.13.0` @ DockerHub

**Additional context**

None

**Comment by kritish-dhaubanjar** [comment]
As you reported, seems like the Preview is not reacting to the checkbox in UI. It appears when you Run the query. :thinking: . Let me fix that. Thanks!

https://github.com/user-attachments/assets/b670d35f-010a-4dbc-a921-ed8c5669797a

**Comment by kritish-dhaubanjar** [comment]
Fixed in https://github.com/kritish-dhaubanjar/dynamodb-dashboard/commit/d77ab0de28c128a160ee5775df5609fd9a439ee5
