### ISSUE TITLE
Feature request: Restoring the table data asynchronously.

### ISSUE THREAD

**Issue by bipinmdr07** [kritish-dhaubanjar/dynamodb-dashboard#221]
**Is your feature request related to a problem? Please describe.**
Currently, when restoring the table data, the restoring of data is done in the serial way i.e. restoring of another table information only happens when the previous table is successfully restored.

**Describe the solution you'd like**
I would like to restore all the tables asynchronously.

**Describe alternatives you've considered**
It would be really great if we could restore the data using multithread as well. This will ensure the faster restore of the data.

**Additional context**

**Comment by kritish-dhaubanjar** [comment]
Resolved in ![feat: change sequential restore of multiple tables -> async](https://github.com/kritish-dhaubanjar/dynamodb-dashboard/commit/051386feffbd9c5bac8d655aa2b776918432d096)
