### ISSUE TITLE
Table column is not updated after attribute in the table is added

### ISSUE THREAD

**Issue by maskeynihal** [kritish-dhaubanjar/dynamodb-dashboard#326]
**Describe the bug**
In the header of the table, a new header column is not added for the new attribute.

**To Reproduce**
1. Add a new attribute to the record
2. View the table
3. The new attribute is not added to the table
4. View the single record, the new attribute can be viewed. 

**Expected behavior**
1. The new attribute column should be added to the table view.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please solve this 😄

**Comment by kritish-dhaubanjar** [comment]
Resolved in [fix(app): add a set of all headers instead of max keys of objects ](https://github.com/kritish-dhaubanjar/dynamodb-dashboard/commit/4633638b8edc5e457eaaea79d754b70b6b54a2ad).

Keys are now generated from all the data loaded in the view.

Thanks!
