### ISSUE TITLE
Generate Table schema

### ISSUE THREAD

**Issue by maskeynihal** [kritish-dhaubanjar/dynamodb-dashboard#479]
**Is your feature request related to a problem? Please describe.**
After the table is created, I need to get the schema of the table so that I use the schema for the integration test. Right now there is no way to get the schema of the table. We can add feature to export table schema. 

**Describe the solution you'd like**
- a button that says `view table schema` an on clicking the button we can view the schema of the table. 
- Add `copy` button so that we can copy the schema

**Describe alternatives you've considered**
The table schema can be generated using AWS CLI for now. 
`aws dynamodb describe-table --table-name this_is_table_name --profile aws_profile_here -
-region us-west-2 > tableSchema.json`

**Additional context**
- N/A

**Comment by kritish-dhaubanjar** [comment]
Resolved in [DynamoDB Dashboard v1.7.0](https://github.com/kritish-dhaubanjar/dynamodb-dashboard/releases/tag/v1.7.0)

Thanks!
