### ISSUE TITLE
Doesn't support linux/arm64

### ISSUE THREAD

**Issue by maskeynihal** [kritish-dhaubanjar/dynamodb-dashboard#618]
**Describe the bug**
It's giving me the error `image with reference docker.io/kritishdhaubanjar/dynamodb-dashboard:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64`

**To Reproduce**
1. Build using M series chip for Mac

**Expected behavior**
- Should support arm chip

**Screenshots**
<img width="1230" alt="image" src="https://github.com/kritish-dhaubanjar/dynamodb-dashboard/assets/26411488/fb1fb671-2e21-497f-bd58-ef3b74042713">

**Comment by JimDabell** [comment]
The Docker image builds just fine on Apple Silicon, so you can probably implement this easily with [a GitHub Action](https://github.com/docker/build-push-action) without needing to bother setting up a Mac.
