### ISSUE TITLE
The table name is shown in Create Table page.

### ISSUE THREAD

**Issue by maskeynihal** [kritish-dhaubanjar/dynamodb-dashboard#771]
**Describe the bug**
The table name is being shown on create table aswell.

**To Reproduce**
1. Go to Create Table
2. On the breadcrumb of page, table name is shown instead of `Create table`

**Expected behavior**
In the breadcrumb `Create Table` should be shown 

**Screenshots**
<img width="1255" alt="image" src="https://github.com/kritish-dhaubanjar/dynamodb-dashboard/assets/26411488/c754a890-5174-421d-814d-d636c7251492">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox
 - Version: 121.0b4

**Comment by kritish-dhaubanjar** [comment]
Thanks! Resolved in [dynamodb-dashboard v1.9.3](https://github.com/kritish-dhaubanjar/dynamodb-dashboard/releases/tag/v1.9.3)
