### ISSUE TITLE
StringSet isn't rendered correctly

### ISSUE THREAD

**Issue by workmanw** [kritish-dhaubanjar/dynamodb-dashboard#788]
**Describe the bug**
I've noticed that StringSet attributes do not render correctly on the item list or when editing the item.

**To Reproduce**

1. Create a test table and add an item with a StringSet attribute. 
2. View the item using dynamodb-dashboard

Using the AWS CLI, LocalStack and `dynamodb-dashboard`: 
```
aws --region us-east-1 --endpoint http://127.0.0.1:4566 dynamodb create-table \
    --table-name TestTable \
    --attribute-definitions AttributeName=ID,AttributeType=S \
    --key-schema AttributeName=ID,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

aws --region us-east-1 --endpoint http://127.0.0.1:4566 dynamodb put-item \
    --table-name TestTable \
    --item '{ "ID": {"S": "1"}, "StringSet": {"SS": ["1", "2", "3"]} }'
    
AWS_REGION="us-east-1" AWS_ENDPOINT="http://127.0.0.1:4566" dynamodb-dashboard start
```

Also the item can be verified as correctly written with:

```
aws --region us-east-1 --endpoint http://127.0.0.1:4566 dynamodb get-item \
    --table-name TestTable \
    --key '{ "ID": {"S": "1"} }'
```

**Screenshots**
<img width="1304" alt="Screenshot 2023-12-04 at 9 13 20 AM" src="https://github.com/kritish-dhaubanjar/dynamodb-dashboard/assets/825487/b7a20f41-2af5-44bc-ad04-47cb58561f2e">
<img width="1308" alt="Screenshot 2023-12-04 at 9 13 28 AM" src="https://github.com/kritish-dhaubanjar/dynamodb-dashboard/assets/825487/b1b09e01-c5c6-48a5-b220-83f424e6f511">
<img width="627" alt="Screenshot 2023-12-04 at 9 15 49 AM" src="https://github.com/kritish-dhaubanjar/dynamodb-dashboard/assets/825487/642ac75b-0e69-4c27-8eff-9322ec1cb66a">

**Additional context**
I'm running version 1.9.3.

Also a big thank you for this great tool!

**Comment by kritish-dhaubanjar** [comment]
@workmanw , Thank you! Looks like DynamoDB SDK returns the items with the `StringSet`, but it's lost during the JSON conversion (reported at https://github.com/aws/aws-sdk-js-v3/issues/3271). Will work on un-marshalling the items correctly.

**Comment by kritish-dhaubanjar** [comment]
Resolved in https://github.com/kritish-dhaubanjar/dynamodb-dashboard/commit/2e8983f1da8da8f81a77ac4c7f1fee61e5e54f2a

**Comment by workmanw** [comment]
@kritish-dhaubanjar I just wanted to confirm that after updating this is fixed on my end as well. Thanks a lot for doing that. I really appreciate it!

**Comment by kritish-dhaubanjar** [comment]
@workmanw , I'll reopen this issue. Please let me know if it's fixed. Thank you!

**Comment by workmanw** [comment]
@kritish-dhaubanjar I think we can keep it closed. I was just confirming that I did retest it and it is fixed. Sorry if that wasn't clear in my prior message.

**Comment by kritish-dhaubanjar** [comment]
Ohh Great! No worries! I'll close the issue then. If there's any issue down the road with sets or other, let us know! Thank you!
